# Generated by Django 3.2.5 on 2021-07-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
